#!/usr/local/bin/bash

#RDBMS type MYSQL, ORACLE, Currently these two are supported
DB_TYPE=MYSQL
DB_DEF_SCHEMA=project_management


## FOR DB_TYPE=MYSQL
MYSQL_USER=root
MYSQL_PASSWORD=evolvus*123
MYSQL_HOST=127.0.0.1
MYSQL_PORT=3306

## FOR DB_TYPE=ORACLE
ORA_SID=ORSID
ORA_USER=SCHM
ORA_PASSWORD=SCHM
ORA_PORT=1551
ORA_HOST=192.1.1.1

COLUMN_BACK_COLOR="blue"
COLUMN_FONT_TYPE="Arial"
COLUMN_FONT_SIZE="12"
COLUMN_HEIGHT="15"

HEADER_BACK_COLOR="yellow"
HEADER_FONT_TYPE="Arial"
HEADER_FONT_SIZE="16"
HEADER_HEIGHT="30"

FLOAT_PATTERN=#,##0.############
DATE_PATTERN="d-MMM-yyyy"
