#!/usr/local/bin/bash


COLUMN_BACK_COLOR="#CEDE1F"
COLUMN_FONT_TYPE=""
COLUMN_FONT_SIZE=""
COLUMN_HEIGHT=""

HEADER_BACK_COLOR="#CEDE1F"
HEADER_FONT_TYPE=""
HEADER_FONT_SIZE=""
HEADER_HEIGHT=""

FLOAT_PATTERN="#,##0.00"
DATE_PATTER="d-M-yyyy"
