#!/usr/local/bin/bash


COLUMN_BACK_COLOR="#CEDE1F"
COLUMN_FONT_TYPE="Utopia"
COLUMN_FONT_SIZE="12"
COLUMN_HEIGHT="15"

HEADER_BACK_COLOR="#CEDE1F"
HEADER_FONT_TYPE="Utopia"
HEADER_FONT_SIZE="16"
HEADER_HEIGHT="30"

FLOAT_PATTERN=#,##0.
DATE_PATTERN="d-MMM-yyyy"
